### ISSUE TITLE
Can't run ./bin/main.dart

### ISSUE THREAD

**Issue by DiegoCarvalho75** [md-weber/dart_koans#12]
Trying to run ./bin/main.dart gives me this error message: 

CreateProcessW failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: pub run --enable-asserts bin\dart_koans_runner.dart
![main](https://user-images.githubusercontent.com/43910549/87233161-91b31000-c39b-11ea-8358-ee85c80a966d.PNG)
![dart_version_pub_get](https://user-images.githubusercontent.com/43910549/87233167-9972b480-c39b-11ea-8768-1e60c9684e9c.PNG)
![debug](https://user-images.githubusercontent.com/43910549/87233178-9e376880-c39b-11ea-9f94-1b7a30192e4f.PNG)
![pub_run](https://user-images.githubusercontent.com/43910549/87233181-a1325900-c39b-11ea-8388-05974bb658ee.PNG)

**Comment by md-weber** [comment]
I see there is a problem with the path. There is an issue with the way in line 11 of the main.dart.

Thanks for the issue I will work on that.

**Comment by md-weber** [comment]
The problem should now be fixed @Caballero75. It would be great if you could test it once more 👍

**Comment by DiegoCarvalho75** [comment]
Everything is ok now. Thanks @md-weber
